#!/bin/bash
set -euo pipefail

# Symlinks are created during install from client tools to kvm-client-wrapper,
# "$0" will tell us which binary was executed. Now exec in the container instead
BIN="$(basename $0)"
ARGS="$@"
CLIENT_UID="$(openssl rand -hex 3)"

ROOT_HOME="-v /root:/root"
RUN_LIBVIRT=$([[ -e /run/libvirt ]] && echo "-v /run/libvirt:/run/libvirt" || echo "")
ETC_LIBVIRT_QEMU=$([[ -e /etc/libvirt/qemu ]] && echo "-v /etc/libvirt/qemu:/etc/libvirt/qemu" || echo "")
LIBVIRT_IMAGES=$([[ -e /var/lib/libvirt/images ]] && echo "-v /var/lib/libvirt/images:/var/lib/libvirt/images" || echo "")
QEMU_FIRMWARE=$([[ -e /usr/share/qemu ]] && echo "-v /usr/share/qemu:/usr/share/qemu" || [[ -e /usr/local/share/qemu ]] && echo "-v /usr/local/share/qemu:/usr/share/qemu" || echo "")
ETC_SSH=$([[ -e /etc/ssh ]] && echo "-v /etc/ssh:/etc/ssh" || echo "")
ETC_VIRT_SCENARIO="-v /etc/virt-scenario:/etc/virt-scenario"
ETC_PVIRSH="-v /etc/pvirsh:/etc/pvirsh"

exec podman run -it --rm --net=host --privileged ${ROOT_HOME} ${RUN_LIBVIRT} ${ETC_LIBVIRT_QEMU} ${LIBVIRT_IMAGES} ${QEMU_FIRMWARE} ${ETC_SSH} ${ETC_VIRT_SCENARIO} ${ETC_PVIRSH} --name kvm-client-${BIN}-${CLIENT_UID} %CONTAINER_IMAGE% ${BIN} ${ARGS}
